name: Repository_Dispatch_Test

on: [repository_dispatch]

jobs:
  hello-world:

    runs-on: self-hosted #windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run PowerShell Hello World script
      if: github.event.action == 'dev'
      run: Write-Output 'Hello World!'
    - name: Run a multi-line PowerShell script
      if: github.event.action == 'dev'
      run: |
        Write-Output "Printing Webhook Action ${{ github.event.action }} ...";
        Write-Output "Printing Webhook Github ${{ github.workflow}}...";
        Write-Output "Printing Webhook Action TEXT ${{ github.event.client_payload.text }} ...";
        Write-Output "Printing CONTEXT $GITHUB_CONTEXT";
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    #- name: Run PowerShell Test script
    #  run: pwsh -command ".\$GITHUB_WORKSPACE\Test-Git.ps1" ${{ github.event.client_payload.text }}
    - name: Run PowerShell Folder Test script
      if: github.event.action == 'dev'
      run: .\PowerShell_Script\Test-Git2.ps1 ${{ github.event.client_payload.text }}
