name: Self-Hosted RUN PS Script

on: 
  workflow_dispatch:
  
jobs:
  hello-world:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Run PowerShell Hello World script
      #if: github.event.action == 'inline'
      run: Write-Output 'Hello World INLINE TEST!'; git config ; git status #echo ${env:PATH}
    - name: Run a Get-Location PowerShell script
      run: Get-Location;
    - name: Run PowerShell Test script
      run: .\Test-Git.ps1
    - name: Run PowerShell Folder Test script
      run: .\PowerShell_Script\Test-Git2.ps1
        
    
